language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "iojs"
before_script:
  - npm i -g gulp jspm codeclimate-test-reporter coveralls
  - node_modules/.bin/webdriver-manager  update
  - npm i
  - jspm i
  - node_modules/.bin/webdriver-manager update
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - jspm dl-loader --traceur
  - gulp test:unit
  - gulp test:e2e
  - jspm dl-loader --Babel
  - gulp test:unit
  - gulp test:e2e
  - gulp report:ci
  - cat report/lcov/firefox/lcov.info | coveralls 

