language: node_js
node_js:
  - "4.2"
  - "5.1"
  - "0.12"
before_script:
  - npm install -g gulp bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - gulp
  - gulp self
  - gulp build
